# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - yearn/yearn-vaults@0.4.3-1sol8

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
      - "@yearnvaults=yearn/yearn-vaults@0.4.3-1sol8"
      #- "@oldyearnvaults=yearn/yearn-vaults@0.3.3"
      

reports:
  exclude_paths:
    - contracts/test/Token.sol

  exclude_contracts:
    - SafeMath
